language: python
matrix:
  include:
    # others still work and don't install python3.7
    - env: TOXENV=py36
      python: 3.6
    - env: TOXENV=py37
      python: 3.7
      dist: xenial
    - env: TOXENV=py37
      dist: xenial
      addons:
        apt:
          sources:
          - deadsnakes
          packages:
          - python3.7-dev
install: pip install tox
script: tox
